### ISSUE TITLE
Most recent pypiper release causes refgenie to fail

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenie#1]
With the most recent update to pypiper, refgenie will now throw the following error when attempting to execute:

`Traceback (most recent call last):
  File "src/refgenie.py", line 19, in <module>
    parser = pypiper.add_pypiper_args(parser)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/utils.py", line 53, in add_pypiper_args
    argument_groups=groups, arguments=args, use_all_args=all_args)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/utils.py", line 571, in _determine_args
    raise TypeError("arguments must be a str or a list.")
TypeError: arguments must be a str or a list.`

**Comment by jpsmith5** [comment]
Updates appear to fix the issue in my testing. Closing for now.
