### ISSUE TITLE
UnboundLocalError: local variable 'updated_relatives' referenced before assignment

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#112]
```
 refgenie tag rCRSd/bowtie2_index:default -t blah
The asset 'rCRSd/bowtie2_index:default' has 0 children and 1 parents. Refgenie will update the relationship data. Do you want to proceed? [y/N] y
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 720, in main
    if not rgc.tag_asset(a["genome"], a["asset"], a["tag"], args.tag):  # tagging in the RefGenConf object
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 384, in tag_asset
    self._update_relatives_tags(genome, asset, tag, new_tag, parents, update_children=True)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 420, in _update_relatives_tags
    self.update_relatives_assets(genome, r_data["item"], r_data["tag"], updated_relatives, update_children)
UnboundLocalError: local variable 'updated_relatives' referenced before assignment
```

**Comment by michalstolarczyk** [comment]
should be resolved with: https://github.com/databio/refgenconf/commit/fee1688d63bf3749eb494322542d165b085f69cd
