### ISSUE TITLE
misleading error message for missing file in REFGENIE variable.

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#121]
If you give `-c file.yaml` for a non-existent file, you get a message that makes sense:

```
nsheff@puma:~/code/refgenconf$ refgenie list -c blah.yaml
Config file path isn't a file: blah.yaml
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 664, in main
    rgc = RefGenConf(filepath=gencfg, writable=False)  # genome cfg will not be updated, create object in read-only mode
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 74, in __init__
    super(RefGenConf, self).__init__(filepath=filepath, entries=entries, writable=writable, wait_max=wait_max)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 89, in __init__
    file_contents = load_yaml(filepath)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 285, in load_yaml
    with open(filepath, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'blah.yaml'
```

If, on the other hand, you a bogus file through the REFGENIE env var, it gives an error that doesn't make sense:

```
nsheff@puma:~/code/refgenconf$ REFGENIE="blah.yaml" refgenie list
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 583, in main
    raise MissingGenomeConfigError(args.genome_config)
refgenie.exceptions.MissingGenomeConfigError: You must provide a config file either as an argument or via an environment variable: REFGENIE
```

**Comment by nsheff** [comment]
I *did* provide a config file (I thought)... It just didn't exist. The error message in that case should be the same as the above, rather than saying "You must provide a config file".

**Comment by michalstolarczyk** [comment]
this will be handled by `yacman.select_config` function

**Comment by michalstolarczyk** [comment]
```
$ cat $REFGENIE 
cat: file.yaml: No such file or directory
$ refgenie list
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 588, in main
    strict_env=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yacman/yacman.py", line 362, in select_config
    format(", ".join(config_env_vars), cfg_file))
FileNotFoundError: Environment variable (REFGENIE) does not point to any existing file: file.yaml
```
