### ISSUE TITLE
Error: checksum doesn't match

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#123]
If I try to build a fasta asset 2 times in a row, it gives an error:

This works:
```
bulker activate databio/refgenie:0.7.0
wget ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/786/075/GCA_000786075.2_hs38d1/GCA_000786075.2_hs38d1_genomic.fna.gz -O hs38d1.fna.gz
refgenie init -c refgenie.yaml
refgenie build -c refgenie.yaml -g hs38d1 -a fasta bowtie2_index --fasta hs38d1.fna.gz
```

Now try:

```
refgenie build -c refgenie.yaml -g hs38d1 -a fasta bowtie2_index --fasta hs38d1.fna.gz
```

```
nsheff@puma:~/code/sandbox$ refgenie build -c refgenie.yaml -g hs38d1 -a fasta bowtie2_index --fasta hs38d1.fna.gz
Output to: hs38d1 /home/nsheff/code/sandbox /home/nsheff/code/sandbox/hs38d1
Removed existing flag: '/home/nsheff/code/sandbox/hs38d1/refgenie_completed.flag'
### Pipeline run code and environment:

*              Command:  `/home/nsheff/.local/bin/refgenie build -c refgenie.yaml -g hs38d1 -a fasta bowtie2_index --fasta hs38d1.fna.gz`
*         Compute host:  puma
*          Working dir:  /home/nsheff/code/sandbox
*            Outfolder:  /home/nsheff/code/sandbox/hs38d1/
*  Pipeline started at:   (10-15 08:04:23) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.5.2
*          Pypiper dir:  `/home/nsheff/.local/lib/python3.5/site-packages/pypiper`
*      Pypiper version:  0.12.0
*         Pipeline dir:  `/home/nsheff/.local/bin`
*     Pipeline version:  None

### Arguments passed to pipeline:

* `asset_registry_paths`:  `['fasta', 'bowtie2_index']`
*            `command`:  `build`
*        `config_file`:  `refgenie.yaml`
*            `context`:  `None`
*             `dbnsfp`:  `None`
*             `docker`:  `False`
*        `ensembl_gtf`:  `None`
*              `fasta`:  `hs38d1.fna.gz`
*        `gencode_gtf`:  `None`
*             `genome`:  `hs38d1`
*      `genome_config`:  `refgenie.yaml`
* `genome_description`:  `None`
*                `gff`:  `None`
*             `logdev`:  `False`
*          `new_start`:  `False`
*          `outfolder`:  `/home/nsheff/code/sandbox`
*            `recover`:  `False`
*            `refgene`:  `None`
*       `requirements`:  `False`
*             `silent`:  `False`
*    `tag_description`:  `None`
*               `tags`:  `None`
*          `verbosity`:  `None`
*            `volumes`:  `None`

----------------------------------------

Inputs required to build 'fasta': fasta
Building asset 'fasta'
Target exists: `/home/nsheff/code/sandbox/hs38d1/fasta/default/build_complete.flag`  

> `cd /home/nsheff/code/sandbox/hs38d1/fasta/default; find . -type f -exec md5sum {} \; | sort -k 2 | awk '{print $1}' | md5sum`
Computing initial genome digest...
Checksum doesn't match

### Pipeline failed at:  (10-15 08:04:24) elapsed: 1.0 _TIME_

Total time: 0:00:01
Failure reason: Pipeline failure. See details above.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 1799, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
Exception: Pipeline failure. See details above.
```

**Comment by nsheff** [comment]
I'm not sure what the expected behavior is here... I guess maybe just note that the asset already exists, and prompt to overwrite? And then if so, it should work to overwrite.

I am not sure 1) why it is checking checksums here, and 2) how the checksums could *not* match, since it's an identical command.

**Comment by michalstolarczyk** [comment]
I could not reproduce this, but I've made some changes to the build code

**Comment by nsheff** [comment]
this was with the old build code.

I've just fixed all the asset build bugs with outfolders that I hadn't tested... hope I didn't step on any toes there. but this error is still there for me...

```
refgenie build -c refgenie.yaml -g hs38d1 -a fasta --fasta hs38d1.fna.gzInputs required to build 'fasta': fasta
Building asset 'fasta'
Output content: /home/nsheff/sandbox/refgenie_bulker/hs38d1; logs: /home/nsheff/sandbox/refgenie_bulker/hs38d1/fasta/default/_refgenie_build
Removed existing flag: '/home/nsheff/sandbox/refgenie_bulker/hs38d1/fasta/default/_refgenie_build/refgenie_completed.flag'
### Pipeline run code and environment:

*              Command:  `/home/nsheff/.local/bin/refgenie build -c refgenie.yaml -g hs38d1 -a fasta --fasta hs38d1.fna.gz`
*         Compute host:  puma
*          Working dir:  /home/nsheff/sandbox/refgenie_bulker
*            Outfolder:  /home/nsheff/sandbox/refgenie_bulker/hs38d1/fasta/default/_refgenie_build/
*  Pipeline started at:   (10-15 08:57:45) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.5.2
*          Pypiper dir:  `/home/nsheff/.local/lib/python3.5/site-packages/pypiper`
*      Pypiper version:  0.12.1
*         Pipeline dir:  `/home/nsheff/.local/bin`
*     Pipeline version:  None

### Arguments passed to pipeline:

* `asset_registry_paths`:  `['fasta']`
*            `command`:  `build`
*        `config_file`:  `refgenie.yaml`
*            `context`:  `None`
*             `dbnsfp`:  `None`
*             `docker`:  `False`
*        `ensembl_gtf`:  `None`
*              `fasta`:  `hs38d1.fna.gz`
*        `gencode_gtf`:  `None`
*             `genome`:  `hs38d1`
*      `genome_config`:  `refgenie.yaml`
* `genome_description`:  `None`
*                `gff`:  `None`
*             `logdev`:  `False`
*          `new_start`:  `False`
*          `outfolder`:  `/home/nsheff/sandbox/refgenie_bulker`
*            `recover`:  `False`
*            `refgene`:  `None`
*       `requirements`:  `False`
*             `silent`:  `False`
*    `tag_description`:  `None`
*               `tags`:  `None`
*          `verbosity`:  `None`
*            `volumes`:  `None`

----------------------------------------

Target exists: `/home/nsheff/sandbox/refgenie_bulker/hs38d1/fasta/default/_refgenie_build/hs38d1_fasta__default.flag`  

> `cd /home/nsheff/sandbox/refgenie_bulker/hs38d1/fasta/default; find . -type f -exec md5sum {} \; | sort -k 2 | awk '{print $1}' | md5sum`

### Pipeline completed. Epilogue
*        Elapsed time (this run):  0:00:00
*  Total elapsed time (all runs):  0:00:01
*         Peak memory (this run):  0 GB
*        Pipeline completed time: 2019-10-15 08:57:45
Computing initial genome digest...
Checksum doesn't match

```

**Comment by michalstolarczyk** [comment]
the checksum check should not happen there. This conditional should be removed since we decided not to use the genome checksums yet, but just display them on the server: https://github.com/databio/refgenie/pull/94#issuecomment-525288114

https://github.com/databio/refgenie/blob/048a82aec032d2d1f73436c515be089f9e7cae21/refgenie/refgenie.py#L470-L473

That said, I've never experienced this problem...

**Comment by nsheff** [comment]
alright, can you just push your local changes? this will go away I presume. sorry if you have to merge with my corrections to the same problems.

**Comment by michalstolarczyk** [comment]
that's ok, I should have pushed that earlier

done

**Comment by nsheff** [comment]
fixed.
