### ISSUE TITLE
docs build failing

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#133]
starting about 90 minutes ago, builds of this started failing.

https://readthedocs.org/projects/refgenie/builds/9835834/

interestingly, this is the first commit that starts failing: 

https://github.com/databio/refgenie/commit/d0f6d6d254e054f6e162e4da2772cb5f89701f2b

**Comment by nsheff** [comment]
could it be related to this?

https://github.com/databio/refgenconf/commit/e528f8dcaa4eb08a324bb2fc7263eab3a2778013

**Comment by nsheff** [comment]
I actually think it's related to https://github.com/databio/refgenieserver/issues/51

Because the docs build gets caught up on pull_asset:

```
rocessing function: list_local
Processing function: list_remote
Processing function: pull_asset
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
...
```

**Comment by nsheff** [comment]
Solved by: 

https://github.com/databio/refgenconf/commit/e974e6705ac9174427e2fb468825415450ab289b
