### ISSUE TITLE
pull without special opts/args throws error

### ISSUE THREAD

**Issue by vreuter** [databio/refgenie#40]
In `refgenconf` the option to preserve a tarball (`unpack=False`) is still deliberately unsupported. Do we want to support that now? If so, `refgenconf` needs to change. If not, we need to make `--unpack`'s meaning be opt-out, e.g. `--preserve-tarball` or something.

**Comment by nsheff** [comment]
I don't have a strong preference. I would say support it if it's relatively easy to do so... it seems it should be pretty simple to implement. but it's not really necessary at this point.

I think either way it should be opt-out -- I'd vote for `--no-untar`

**Comment by michalstolarczyk** [comment]
yeah, the `NotImplementedError` bothered me as well, good point.

`--no-untar` seems ok to me

**Comment by nsheff** [comment]
just running a test pull throws an error:

```
refgenie -c test.yaml pull
Starting pull for 'hg38/bowtie2'
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 429, in main
    rgc.pull_asset(args.genome, args.asset, genome_config_path, unpack=not args.no_untar)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 224, in pull_asset
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 224, in <listcomp>
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 247, in _pull_asset
    archive_data = _download_json(url_json)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenconf/refgenconf.py", line 365, in _download_json
    return json.loads(server_resp.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by nsheff** [comment]
Ilm not sure why but I don't seem to be able to actually pull anything.

**Comment by michalstolarczyk** [comment]
does [that](5d99d9b753d7b3ed03150b3b15fbb5a4b9afc009) solve your issue?

**Comment by vreuter** [comment]
I haven't fully updated my local config file, so please excuse the mixed (old/new) formatting, but a quick tests works for me on Python 3.5.2 with `dev` of `refgenconf` and `refgenie` (and `yacman 0.4dev`):
```
(py3.5) vr @ ~/code/refgenie
dev└─ $ refgenie pull -c $REFGENIE -g hg38 -a bowtie2
Starting pull for 'hg38/bowtie2'
'hg38/bowtie2' archive size: 3.5GB
Downloading URL: http://refgenomes.databio.org/asset/hg38/bowtie2/archive
hg38/bowtie2:   1%|█                                                                                                                                                   | 28.5M/3.75G [00:12<23:10, 2.68MB/s]^C
The download was interrupted
Incomplete file '/home/vr/genomes/hg38/bowtie2.tar' was removed
hg38/bowtie2:   1%|█▏                                                                                                                                                  | 28.7M/3.75G [00:12<26:07, 2.37MB/s]
(py3.5) vr @ ~/code/refgenie
dev└─ $ cat $REFGENIE 
genome_folder: $GENOMES
genome_server: http://refgenomes.databio.org
genomes:
  hg38:
    bowtie2: indexed_bowtie2
    hisat2: indexed_hisat2
    indexed_bowtie2: indexed_bowtie2
  mm10:
    indexes:
      bowtie2: indexed_bowtie2
  rCRS:
    bowtie2_index:
      path: indexed_bowtie2
    indexed_bowtie2:
      path: rCRS/indexed_bowtie2
    indexed_hisat2:
      path: rCRS/indexed_hisat2
    indexed_kallisto:
      path: rCRS/indexed_kallisto
```

**Comment by vreuter** [comment]
Side note--cool that we remove incomplete downloads!

**Comment by michalstolarczyk** [comment]
```
hg38/bowtie2:   1%|▏                           | 19.5M/3.75G [00:01<04:08, 15.0MB/s]
```

I noticed that these download stats do not show up next to the progress bar in your case

OS discrepancy?

**Comment by vreuter** [comment]
> ```
> hg38/bowtie2:   1%|▏                           | 19.5M/3.75G [00:01<04:08, 15.0MB/s]
> ```
> 
> I noticed that these download stats do not show up next to the progress bar in your case
> 
> OS discrepancy? Or you have not copied them?

They're there, just way over to the side--sorry for the confusion

**Comment by michalstolarczyk** [comment]
is it good to close?

**Comment by vreuter** [comment]
Yep, my reason for opening this is resolved!
