### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#41]
using the test example, I can't really run anything here

using dev branch of refgenie and

 ```
refgenie init -c test.yaml
Initializing refgenie genome configuration
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 394, in main
    refgenie_init(args.genome_config, args.genome_server)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 352, in refgenie_init
    CFG_FOLDER_KEY: os.path.dirname(os.path.abspath(genome_config_path)),
  File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by nsheff** [comment]
I solved this ( I think)
