### ISSUE TITLE
init broken

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#42]
why does refgenie init now want a "GENOME_SERVER" (which should be not required) and no longer needs a config file name to init?

```
refgenie init --help
version: 0.4.0-dev
usage: refgenie init [-h] [-s GENOME_SERVER]

Initialize a genome configuration.

optional arguments:
  -h, --help            show this help message and exit
  -s GENOME_SERVER, --genome-server GENOME_SERVER
```

Running it empty is just broken:

```
refgenie init
Initializing refgenie genome configuration
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 394, in main
    refgenie_init(args.genome_config, args.genome_server)
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 352, in refgenie_init
    CFG_FOLDER_KEY: os.path.dirname(os.path.abspath(genome_config_path)),
  File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Related to #11?

**Comment by michalstolarczyk** [comment]
similar to: #43 

works when used like:
```
[mstolarczyk@MichalsMBP ~]: refgenie -c ~/test.yaml init -s test
Initializing refgenie genome configuration
Wrote new refgenie genome configuration file: /Users/mstolarczyk/test.yaml
[mstolarczyk@MichalsMBP ~]: cat /Users/mstolarczyk/test.yaml 
genome_folder: /Users/mstolarczyk
genome_server: test
genomes: OrderedDict()
```

**Comment by nsheff** [comment]
Ok right, I'm an idiot.
