### ISSUE TITLE
refgenie list is broken

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#43]
```
refgenie list -c test.yaml 
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 399, in main
    raise MissingGenomeConfigError(args.genome_config)
refgenie.exceptions.MissingGenomeConfigError: You must provide a config file either as an argument or via an environment variable: ['REFGENIE']
```

I did provide a config file...

**Comment by michalstolarczyk** [comment]
`-c` is tied to the main parser, so it's: `refgenie -c test.yaml list`


```
[mstolarczyk@MichalsMBP ~]: refgenie -c test.yaml list
'genomes' value is a str, not a PathExAttMap; setting to empty PathExAttMap
Local genomes: 
Local assets:
```

**Comment by nsheff** [comment]
:man_facepalming: Ok -- do you think it's worth changing that? apparently it had me fooled...
