### ISSUE TITLE
ValueError: To create config object, string should be config filepath; got 'genome_config.yaml'

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#48]
weird error message:

```
>>> rgc = refgenconf.RefGenConf("genome_config.yaml")
Can't load config file 'genome_config.yaml'
FileNotFoundError[Errno 2] No such file or directory: 'genome_config.yaml'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheffien/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 51, in __init__
    "be config filepath; got '{}'".format(entries))
ValueError: To create config object, string should be config filepath; got 'genome_config.yaml'
```
I *did* provide a filepath. it just didn't exist...

**Comment by vreuter** [comment]
OK; what would you like it to instead say?
