### ISSUE TITLE
In driver function, broaden use of determined genome config path

### ISSUE THREAD

**Issue by jpsmith5** [databio/refgenie#54]
Calling `refgenie init` alone generates a cryptic error (see below). Would be helpful to get a usage type message.
```
$ refgenie init
Initializing refgenie genome configuration
Traceback (most recent call last):
  File "/home/jps3dp/.local/bin/refgenie", line 11, in <module>
    load_entry_point('refgenie==0.4.0.dev0', 'console_scripts', 'refgenie')()
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 426, in main
    _writeable(os.path.dirname(args.genome_config), strict_exists=True)
  File "/usr/lib/python3.6/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
Similarly, I forgot to include a `-c` when pointing to my `config.yaml` file and it throws the same message as providing no further input.  Again, either a usage type message or a `-c` is required type message would be helpful.

```
$ refgenie init $REFGENIE
Initializing refgenie genome configuration
Traceback (most recent call last):
  File "/home/jps3dp/.local/bin/refgenie", line 11, in <module>
    load_entry_point('refgenie==0.4.0.dev0', 'console_scripts', 'refgenie')()
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 426, in main
    _writeable(os.path.dirname(args.genome_config), strict_exists=True)
  File "/usr/lib/python3.6/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by vreuter** [comment]
We should just determine the config in the driver, rather than repeating access to `args.genome_config`

**Comment by nsheff** [comment]
error message is now sane.
