### ISSUE TITLE
refgenie init error: Config file path isn't a file

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#58]
I think the issue arose after https://github.com/databio/refgenie/commit/291320885837197420e37dc854a461bf88a52ea4

```
[mstolarczyk@MichalsMBP ~]: refgenie --verbosity 5 init -c ~/genome_folder/genome_config.yaml
[2019-06-14 22:22:19,063] {logmuse:258} (init_logger) [DEBUG] > Configured logger 'logmuse' using logmuse v0.2.0 
[2019-06-14 22:22:19,063] {refgenconf:258} (init_logger) [DEBUG] > Configured logger 'refgenconf' using logmuse v0.2.0 
[2019-06-14 22:22:19,063] {logmuse:420} (main) [DEBUG] > Args: Namespace(command='init', genome_config='/Users/mstolarczyk/genome_folder/genome_config.yaml', genome_server='http://refgenomes.databio.org', logdev=False, silent=False, verbosity='5') 
Config file path isn't a file: /Users/mstolarczyk/genome_folder/genome_config.yaml
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 427, in main
    gencfg = select_genome_config(args.genome_config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/helpers.py", line 20, in select_genome_config
    return yacman.select_config(filename, conf_env_vars or CFG_ENV_VARS)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yacman/yacman.py", line 90, in select_config
    raise IOError(config_filepath)
OSError: /Users/mstolarczyk/genome_folder/genome_config.yaml
```

**Comment by vreuter** [comment]
Couple issues here...
1. For this and analogous cases, `yacman` should probably parameterize the severity of rxn to a nonexistent config file.
2. Probably the genome config file should be required for `init`--I think the implicit nature of the environment variable makes sense for acquainted users, but for a new user / initial setup, the specification should probably be explicit.

**Comment by vreuter** [comment]
> I think the issue arose after [2913208](https://github.com/databio/refgenie/commit/291320885837197420e37dc854a461bf88a52ea4)

Yes, previous placement of the call to `yacman` (after the `INIT_CMD` block) allowed this to work, but that's an that bakes in intimate knowledge of control flow state and is therefore fragile, as revealed here.

**Comment by vreuter** [comment]
https://github.com/databio/refgenie/pull/60/commits/cebd84b500afeb8add4206bf6d2b09431bbf901c
