### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#63]
This should work without error:
```
nsheff@puma:~$ export REFGENIE='genomes.yaml'
nsheff@puma:~$ refgenie init
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/refgenie/refgenie.py", line 431, in main
    raise MissingGenomeConfigError(args.genome_config)
refgenie.exceptions.MissingGenomeConfigError: You must provide a config file either as an argument or via an environment variable: ['REFGENIE']
nsheff@puma:~$ echo $REFGENIE
genomes.yaml
```

```
 refgenie --version
refgenie 0.4.1
```

**Comment by nsheff** [comment]
Related to #59.

**Comment by nsheff** [comment]
In light of discussion in #59 I agree with @vreuter we should require the config passed to -c, but change the error message so it doesn't say "either...." indicating that the env variable is appropriate for the `init` call.

**Comment by vreuter** [comment]
Can you type out the desired message? I can't parse what you mean.
