### ISSUE TITLE
allow listing for individual genomes

### ISSUE THREAD

**Issue by nsheff** [databio/refgenie#84]
I want to do:

```
refgenie list -g hg38
```

but it shows everything.

**Comment by nsheff** [comment]
```
refgenie list
refgenie 0.6.0
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 445, in main
    pfx, genomes, assets, recipes = _exec_list(rgc, args.command == LIST_REMOTE_CMD, args.genome)
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 357, in _exec_list
    assemblies, assets = rgc.list_local(genome=genome)
TypeError: list_local() got an unexpected keyword argument 'genome'
```

```
refgenie list -g hg38
refgenie 0.6.0
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 445, in main
    pfx, genomes, assets, recipes = _exec_list(rgc, args.command == LIST_REMOTE_CMD, args.genome)
  File "/home/nsheff/.local/lib/python3.7/site-packages/refgenie/refgenie.py", line 357, in _exec_list
    assemblies, assets = rgc.list_local(genome=genome)
TypeError: list_local() got an unexpected keyword argument 'genome'

```

**Comment by nsheff** [comment]
you just forgot to bump the minimim version of refgenconf required.
