### ISSUE TITLE
refgenie build RecursionError

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#89]
builder fails when building `fasta` asset from fasta files with large number of headers.
For instance it worked fine with DNA sequences in `hg38.fa.gz`, but errors when run with `hg38_cdna.fa.gz`. 

**Header count comparison:**
```
[mjs5kd@udc-ba36-36 fasta]: pwd
/project/shefflab/genomes/hg38/fasta
[mjs5kd@udc-ba36-36 fasta]: grep '>' hg38.fa | wc -l
455
[mjs5kd@udc-ba36-36 fasta]: grep '>' ../../hg38_cdna/fasta/hg38_cdna.fa | wc -l
189154
```
## Traceback
```
Traceback (most recent call last):
  File "/home/mjs5kd/.local/bin/refgenie", line 11, in <module>
    sys.exit(main())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 503, in main
    refgenie_build(rgc, args)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 383, in refgenie_build
    refgenie_initg(rgc, genome, collection_checksum, contents)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 257, in refgenie_initg
    rgc.write()
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/yacman/yacman.py", line 61, in write
    f.write(self.to_yaml())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 161, in to_yaml
    return "\n".join(self.get_yaml_lines()) + ("\n" if trailing_newline else "")
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 117, in get_yaml_lines
    conversions=conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 218, in _simplify_keyvalue
    v = self._simplify_keyvalue(list(v.items()), build, build())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  [Previous line repeated 1 more times]
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 218, in _simplify_keyvalue
    v = self._simplify_keyvalue(list(v.items()), build, build())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 218, in _simplify_keyvalue
    v = self._simplify_keyvalue(list(v.items()), build, build())
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 225, in _simplify_keyvalue
    return self._simplify_keyvalue(kvs, build, acc, conversions)
  [Previous line repeated 966 more times]
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/_att_map_like.py", line 217, in _simplify_keyvalue
    if is_custom_map(v):
  File "/home/mjs5kd/.local/lib/python3.6/site-packages/attmap/helpers.py", line 93, in is_custom_map
    return isinstance(obj, Mapping) and type(obj) is not dict
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/abc.py", line 190, in __instancecheck__
    subclass in cls._abc_negative_cache):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by nsheff** [comment]
seems like a problem with python. i hadn't thought of that but for transcriptomes or other things with tons of chromosomes, it's going to be huge to store the 'content' block.

**Comment by nsheff** [comment]
I propose we do the following:

- no longer store the 'content' block in the refgenie config file. Instead, only store the final genome checksum. The chr checksums (the content block) should be stored as a tsv file within the fasta asset folder.
so:
```
chr1  hash
chr2  hash
chr3  hash
```
this could be 160,000 lines in the case of the transcriptome, or only 20ish lines for a genome. I believe there's no real reason to store these in the genome config anyway; even when it was only 25 all it did was add clutter.

**Comment by michalstolarczyk** [comment]
Ok, makes sense. I can take care of that
