### ISSUE TITLE
TypeError in build_argparser

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/refgenie#99]
```
refgenie init -c genomes.yaml

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 468, in main
    parser = logmuse.add_logging_options(build_argparser())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 70, in build_argparser
    version=__version__)
TypeError: __init__() got an unexpected keyword argument 'version'
```

**Comment by nsheff** [comment]
that's interesting. what version of ubiquerg are you using?
can you try the dev ubiquerg?

**Comment by michalstolarczyk** [comment]
I'm using 0.4.8, which is the dev one
